# Project Information
site_name: Red Hat OpenShift Service on AWS
site_url: https://rosaworkshop.io
site_description: A guided workshop that ranges from application deployment to cluster configuration for ROSA clusters.
site_author: Red Hat

# Repository
repo_name: openshift-cs/rosaworkshop
repo_url: https://github.com/openshift-cs/rosaworkshop

# Nav Menu Definition
nav:
  - Introduction: index.md
  - Prerequisites: 1-prereqs.md
  - Cluster Creation: 1b-create_amro.md
  - Concepts: 2-concepts.md
  - Lab Overview: 3-lab_overview.md
  - Deployment: 4-deployment.md
  - Health Check: 5-healthcheck.md
  - Storage: 6-storage.md
  - ConfigMaps, Secrets, Env Var: 7-confsecenv.md
  - Networking: 8-networking.md
  - Logging: 9-logging.md
  - S2I Deployments: 10-deployment_s2i.md
  - S2I Webhooks for CICD: 11-cicd_s2i.md
  - Autoscaling: 12-hpa.md
  - Feedback: feedback.md

# Theme Configuration
theme:
  name: material
  language: 'en'
  palette:
    primary: black
    accent: red
  font:
    text: Overpass
    code: Overpass Mono
  logo: images/favicon.ico
  favicon: images/favicon.ico
docs_dir: AMRO

# Extensions
markdown_extensions:
  - toc:
      permalink: "#"

# Google Analytics
google_analytics:
  - 'UA-30752912-5'
  - 'auto'
